package paquete_principal;

import Filosofo.Tenedores;
import java.awt.Color;
import java.applet.Applet;
import java.awt.Graphics;
import java.awt.Font;
import java.awt.geom.AffineTransform;
import javax.swing.JLabel;
import java.util.Random;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lopez
 */
public class principal extends javax.swing.JFrame {
    //Declarar arreglo
 
    JLabel tenedor[];
    //variables: 
    int pos_filo, lado_izq = 0, lado_der = 0;
    Tenedores tenedor2;

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        comida1.setVisible(false);
        comida2.setVisible(false);
        comida3.setVisible(false);
        comida4.setVisible(false);
        comida5.setVisible(false);
        diseñotenedor(Tenedor1);
        diseñotenedor(Tenedor2);
        diseñotenedor(Tenedor3);
        diseñotenedor(Tenedor4);
        diseñotenedor(Tenedor5);
        
        this.setLocationRelativeTo(this);
    }
public void diseñotenedor(JLabel x){
            x.setText("Disponible");
        x.setForeground(Color.red);
        x.setFont(Font.decode("Tahoma"));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Tenedor1 = new javax.swing.JLabel();
        Tenedor2 = new javax.swing.JLabel();
        Tenedor3 = new javax.swing.JLabel();
        Tenedor4 = new javax.swing.JLabel();
        Tenedor5 = new javax.swing.JLabel();
        IniciarT = new javax.swing.JButton();
        filosofo1 = new javax.swing.JLabel();
        filosofo2 = new javax.swing.JLabel();
        filosofo3 = new javax.swing.JLabel();
        filosofo4 = new javax.swing.JLabel();
        filosofo5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comida1 = new javax.swing.JLabel();
        comida2 = new javax.swing.JLabel();
        comida3 = new javax.swing.JLabel();
        comida4 = new javax.swing.JLabel();
        comida5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tenedor1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tenedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(Tenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        Tenedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(Tenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        Tenedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(Tenedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        Tenedor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(Tenedor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        Tenedor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(Tenedor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        IniciarT.setBackground(new java.awt.Color(153, 153, 255));
        IniciarT.setFont(new java.awt.Font("Yaahowu", 1, 12)); // NOI18N
        IniciarT.setForeground(new java.awt.Color(0, 0, 0));
        IniciarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/plate.png"))); // NOI18N
        IniciarT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IniciarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarTActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HeracilitoPiensa.jpg"))); // NOI18N
        getContentPane().add(filosofo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        filosofo1.getAccessibleContext().setAccessibleName("filosofo1");

        filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PitagorasPiensa.jpg"))); // NOI18N
        getContentPane().add(filosofo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));
        filosofo2.getAccessibleContext().setAccessibleName("filosofo2");

        filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SocratesPiensa.jpg"))); // NOI18N
        getContentPane().add(filosofo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MiletoPiensa.jpg"))); // NOI18N
        getContentPane().add(filosofo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        filosofo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DemocritoPiensa.jpg"))); // NOI18N
        getContentPane().add(filosofo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Heráclito de Efeso");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Demócrito de Abdera");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tales de Mileto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Sócrates");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Pitágoras");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        comida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carne2.jpg"))); // NOI18N
        comida1.setName("Carne"); // NOI18N
        getContentPane().add(comida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));
        comida1.getAccessibleContext().setAccessibleName("Carne");

        comida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ensalada2.jpg"))); // NOI18N
        getContentPane().add(comida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));
        comida2.getAccessibleContext().setAccessibleName("Ensalada");

        comida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fideos2.jpg"))); // NOI18N
        getContentPane().add(comida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 60, 30));
        comida3.getAccessibleContext().setAccessibleName("Fideos");

        comida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papas2.jpg"))); // NOI18N
        getContentPane().add(comida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));
        comida4.getAccessibleContext().setAccessibleName("Papas");

        comida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ensalada2.jpg"))); // NOI18N
        getContentPane().add(comida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        fondo.setBackground(new java.awt.Color(102, 102, 102));
        fondo.setForeground(new java.awt.Color(102, 102, 102));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoesti.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarTActionPerformed
        IniciarT.setEnabled(false);//Esto para evitar que hayan mas de 5 hilos ejecutandose
        //Agregar arreglos de los filosofos 
        String[] comida = {"Fideos", "Carne", "Papas fritas", "Ensalada"};      
        //Arreglo de Tenedores 
        tenedor = new JLabel[5];
        tenedor[0] = Tenedor1;
        tenedor[1] = Tenedor2;
        tenedor[2] = Tenedor3;
        tenedor[3] = Tenedor4;
        tenedor[4] = Tenedor5;
        //ver el que tenedor estamos utilizando
        for (pos_filo = 0; pos_filo < 5; pos_filo = pos_filo + 1) {
            // la posicion para el tenedor izquierdo seria la posicion del filosofo -1
            lado_izq = pos_filo - 1;
            //Cuando la posicion de filosofo es la primera
            if (lado_izq < 0) {
                //Seria la ultima posición de tenedores
                lado_izq = 4;
            }
            Random rand = new Random();
            int random = rand.nextInt(4);
            //en este caso la posicion de su tenedor es el que sigue (derecho)
            lado_der = pos_filo;
            //Mandamos la posicion, si esta en el lado derecho o izquierdo 
           tenedor2 = new Tenedores(pos_filo, tenedor[lado_izq], tenedor[lado_der], comida[random], filosofo1, filosofo2, filosofo3, filosofo4, filosofo5, comida1, comida2, comida3, comida4, comida5);
           // tenedor2 = new Tenedores(pos_filo, tenedor[lado_izq], tenedor[lado_der], filosofo[pos_filo]);

        }
    }//GEN-LAST:event_IniciarTActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarT;
    public javax.swing.JLabel Tenedor1;
    public javax.swing.JLabel Tenedor2;
    public javax.swing.JLabel Tenedor3;
    public javax.swing.JLabel Tenedor4;
    public javax.swing.JLabel Tenedor5;
    private javax.swing.JLabel comida1;
    private javax.swing.JLabel comida2;
    private javax.swing.JLabel comida3;
    private javax.swing.JLabel comida4;
    private javax.swing.JLabel comida5;
    private javax.swing.JLabel filosofo1;
    private javax.swing.JLabel filosofo2;
    private javax.swing.JLabel filosofo3;
    private javax.swing.JLabel filosofo4;
    private javax.swing.JLabel filosofo5;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
