package paquete_principal;

import Filosofo.Tenedores;
import javax.swing.JLabel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lopez
 */
public class principal extends javax.swing.JFrame {
    //Declarar arreglo
    JLabel tenedor[];
    //variables: 
    int pos_filo, lado_izq=0, lado_der = 0;
    Tenedores tenedor2;
    
    
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Tenedor1 = new javax.swing.JLabel();
        Tenedor2 = new javax.swing.JLabel();
        Tenedor3 = new javax.swing.JLabel();
        Tenedor4 = new javax.swing.JLabel();
        Tenedor5 = new javax.swing.JLabel();
        IniciarT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tenedor1.setText("Tenedor 1");

        Tenedor2.setText("Tenedor 2");

        Tenedor3.setText("Tenedor 3");

        Tenedor4.setText("Tenedor 4");

        Tenedor5.setText("Tenedor 5");

        IniciarT.setText("Iniciar");
        IniciarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tenedor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(Tenedor3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tenedor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tenedor4)))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IniciarT)
                    .addComponent(Tenedor5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tenedor1)
                    .addComponent(Tenedor4))
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tenedor3)
                    .addComponent(Tenedor2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Tenedor5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(IniciarT)
                .addGap(221, 221, 221))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarTActionPerformed

    //Agregar arreglos de los filosofos 
    
    //Arreglo de Tenedores 
    tenedor = new JLabel[5];
    tenedor[0] = Tenedor1;
    tenedor[1] = Tenedor2;
    tenedor[2] = Tenedor3;
    tenedor[3] = Tenedor4;
    tenedor[4] = Tenedor5;
 
    //ver el que tenedor estamos utilizando
    for (pos_filo = 0; pos_filo < 5; pos_filo=pos_filo+1) {
            // la posicion para el tenedor izquierdo seria la posicion del filosofo -1
            lado_izq= pos_filo- 1; 
            //Cuando la posicion de filosofo es la primera
            if (lado_izq < 0) {
              //Seria la ultima posición de tenedores
                lado_izq= 4;
            }
            //en este caso la posicion de su tenedor es el que sigue (derecho)
            lado_der = pos_filo;
            //Mandamos la posicion, si esta en el lado derecho o izquierdo 
            tenedor2 = new Tenedores(pos_filo, tenedor[lado_izq], tenedor[lado_der]);
        }
    
    }//GEN-LAST:event_IniciarTActionPerformed
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarT;
    public javax.swing.JLabel Tenedor1;
    public javax.swing.JLabel Tenedor2;
    public javax.swing.JLabel Tenedor3;
    public javax.swing.JLabel Tenedor4;
    public javax.swing.JLabel Tenedor5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
