package paquete_principal;

import Filosofo.Tenedores;
import java.awt.geom.AffineTransform;
import javax.swing.JLabel;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lopez
 */
public class principal extends javax.swing.JFrame {

    //Declarar arreglo
    JLabel tenedor[];
    //variables: 
    int pos_filo, lado_izq = 0, lado_der = 0;
    Tenedores tenedor2;

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        comida1.setVisible(false);
        comida2.setVisible(false);
        comida3.setVisible(false);
        comida4.setVisible(false);
        comida5.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Tenedor1 = new javax.swing.JLabel();
        Tenedor2 = new javax.swing.JLabel();
        Tenedor3 = new javax.swing.JLabel();
        Tenedor4 = new javax.swing.JLabel();
        Tenedor5 = new javax.swing.JLabel();
        IniciarT = new javax.swing.JButton();
        filosofo1 = new javax.swing.JLabel();
        filosofo2 = new javax.swing.JLabel();
        filosofo3 = new javax.swing.JLabel();
        filosofo4 = new javax.swing.JLabel();
        filosofo5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comida1 = new javax.swing.JLabel();
        comida2 = new javax.swing.JLabel();
        comida3 = new javax.swing.JLabel();
        comida4 = new javax.swing.JLabel();
        comida5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tenedor1.setText("Tenedor 1");

        Tenedor2.setText("Tenedor 2");

        Tenedor3.setText("Tenedor 3");

        Tenedor4.setText("Tenedor 4");

        Tenedor5.setText("Tenedor 5");

        IniciarT.setText("Iniciar");
        IniciarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarTActionPerformed(evt);
            }
        });

        filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HeracilitoPiensa.jpg"))); // NOI18N

        filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PitagorasPiensa.jpg"))); // NOI18N

        filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SocratesPiensa.jpg"))); // NOI18N

        filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MiletoPiensa.jpg"))); // NOI18N

        filosofo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DemocritoPiensa.jpg"))); // NOI18N

        jLabel6.setText("Heráclito de Efeso");

        jLabel7.setText("Demócrito de Abdera");

        jLabel8.setText("Tales de Mileto");

        jLabel9.setText("Sócrates");

        jLabel10.setText("Pitágoras");

        comida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carne2.jpg"))); // NOI18N
        comida1.setName("Carne"); // NOI18N

        comida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ensalada2.jpg"))); // NOI18N

        comida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fideos2.jpg"))); // NOI18N

        comida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papas2.jpg"))); // NOI18N

        comida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ensalada2.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(filosofo1)
                        .addGap(18, 18, 18)
                        .addComponent(comida1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(comida3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filosofo3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel8)))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(filosofo5)
                                        .addGap(68, 68, 68)
                                        .addComponent(Tenedor5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Tenedor2)
                                        .addGap(91, 91, 91)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel10))
                                            .addComponent(filosofo2)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tenedor1)
                                .addGap(102, 102, 102)
                                .addComponent(comida5)
                                .addGap(100, 100, 100)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tenedor3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(filosofo4)
                                            .addComponent(comida4))
                                        .addGap(31, 31, 31)
                                        .addComponent(Tenedor4))))
                            .addComponent(comida2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(IniciarT)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tenedor1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filosofo5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(Tenedor5)))
                                .addGap(18, 18, 18)
                                .addComponent(comida5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tenedor4)
                                    .addComponent(filosofo4))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comida4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(comida1)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filosofo3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(filosofo1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(filosofo2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(comida3))
                                .addGap(22, 22, 22)
                                .addComponent(Tenedor3))
                            .addComponent(comida2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(Tenedor2)
                        .addGap(97, 97, 97)
                        .addComponent(IniciarT)
                        .addGap(28, 28, 28))))
        );

        filosofo1.getAccessibleContext().setAccessibleName("filosofo1");
        filosofo2.getAccessibleContext().setAccessibleName("filosofo2");
        comida1.getAccessibleContext().setAccessibleName("Carne");
        comida2.getAccessibleContext().setAccessibleName("Ensalada");
        comida3.getAccessibleContext().setAccessibleName("Fideos");
        comida4.getAccessibleContext().setAccessibleName("Papas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarTActionPerformed
        IniciarT.setEnabled(false);//Esto para evitar que hayan mas de 5 hilos ejecutandose
        //Agregar arreglos de los filosofos 
        String[] comida = {"Fideos", "Carne", "Papas fritas", "Ensalada"};
        //Arreglo de Tenedores 
        tenedor = new JLabel[5];
        tenedor[0] = Tenedor1;
        tenedor[1] = Tenedor2;
        tenedor[2] = Tenedor3;
        tenedor[3] = Tenedor4;
        tenedor[4] = Tenedor5;
        //ver el que tenedor estamos utilizando
        for (pos_filo = 0; pos_filo < 5; pos_filo = pos_filo + 1) {
            // la posicion para el tenedor izquierdo seria la posicion del filosofo -1
            lado_izq = pos_filo - 1;
            //Cuando la posicion de filosofo es la primera
            if (lado_izq < 0) {
                //Seria la ultima posición de tenedores
                lado_izq = 4;
            }
            Random rand = new Random();
            int random = rand.nextInt(4);
            //en este caso la posicion de su tenedor es el que sigue (derecho)
            lado_der = pos_filo;
            //Mandamos la posicion, si esta en el lado derecho o izquierdo 
            tenedor2 = new Tenedores(pos_filo, tenedor[lado_izq], tenedor[lado_der], comida[random], filosofo1, filosofo2, filosofo3, filosofo4, filosofo5, comida1, comida2, comida3, comida4, comida5);
            //tenedor2 = new Tenedores(pos_filo, tenedor[lado_izq], tenedor[lado_der], comida[random]);

        }

    }//GEN-LAST:event_IniciarTActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarT;
    public javax.swing.JLabel Tenedor1;
    public javax.swing.JLabel Tenedor2;
    public javax.swing.JLabel Tenedor3;
    public javax.swing.JLabel Tenedor4;
    public javax.swing.JLabel Tenedor5;
    private javax.swing.JLabel comida1;
    private javax.swing.JLabel comida2;
    private javax.swing.JLabel comida3;
    private javax.swing.JLabel comida4;
    private javax.swing.JLabel comida5;
    private javax.swing.JLabel filosofo1;
    private javax.swing.JLabel filosofo2;
    private javax.swing.JLabel filosofo3;
    private javax.swing.JLabel filosofo4;
    private javax.swing.JLabel filosofo5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
